version: '2'
services:
  test:
    image: gfw/pipe-tools
    build: .
    command: py.test tests
    volumes:
      - "./:/opt/project"

  bash:
    image: gfw/pipe-tools
    build: .
    command: bash
    volumes:
      - "./:/opt/project"
